## Risk-groups parameters ##
Exp_claims =  { A = 0.01,  B = 0.02}
Ratio_of_types =  { A = 50,  B = 50}      
max_nbr_of_claims = 2

## BMS parameters ##
nbr_of_classes =  5
rule_type = "S" #>>> Can be : "S" or "M"




## Model parameters ##
model_type = "stp"
add_constraints = []    #>>> Can be : ["ir", "pr", "oc"]
premium_type = "TR1"
Transition_rules =  [1, -3]
periods =  0


## Solver parameters ##
file_name =  "optimal_solution.xlsx"
solver = "Gurobi"
approx = 0
consol = 1


#OTHER????
class_min = 3
class_max = 100

round = 4
