## Risk-groups parameters ##
Exp_claims =  { A = 0.01,  B = 0.02}
Ratio_of_types =  { A = 50,  B = 50}     
Obs_claims =  {A = 0.01, B = 0.03}
max_nbr_of_claims = 2

## BMS parameters ##
nbr_of_classes =  5
rule_type = "U" #>>> Can be : "U" or "NU"


## Model parameters ##
model_type = "joint"      #>>> Can be: "stp", "TR", "PR", "joint"
add_constraints = []    #>>> Can be : ["ir", "pr", "oc"]
premium_type = "max" #If model_type TR, then it can be: "prop" (def), "lin", "min", "max"
Transition_rules =  [1, -2]
periods =  0
observable ="True"

## Solver parameters ##
solver = "Gurobi" #"GLPK"#
approx = 0
    # "one_imp"
    #"class_extreme"  
    #"iter" 
consol = 1
round = 4
