## Risk-groups parameters ##
Exp_claims =  { A = 0.01,  B = 0.02}
Ratio_of_types =  { A = 50,  B = 50}      
max_nbr_of_claims = 2

## BMS parameters ##
nbr_of_classes =  5
rule_type = "U" #>>> Can be : "U" or "NU"




## Model parameters ##
model_type = "joint"      #>>> Can be: "stp", "TR", "PR", "joint"
add_constraints = []    #>>> Can be : ["ir", "pr", "oc"]
premium_type = "max" #If model_type TR, then it can be: "prop" (def), "lin", "min", "max"
Transition_rules =  [1, -2]
periods =  10


## Solver parameters ##
file_name =  "optimal_solution.xlsx"
solver = "Gurobi"

approx = 0   
#If 0, then exact model, other options: 

consol = 1


#OTHER????
class_min = 3
class_max = 100

round = 4
